# INFLUXDB_ADDR="http://10.0.0.5:9086" DB_HOST="127.0.0.1" ./datastream in-server -l :8084

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-router-cfg
  namespace: powerp
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update k8s.io/k8s.io/README.md when you update this file
  router.conf: |
    server {
        listen 80;

        client_header_buffer_size 1024k;
        large_client_header_buffers 4 1024k;

        location / {
            resolver 10.254.1.1;
            proxy_read_timeout 1800;
            proxy_pass_header Server;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_pass http://$arg_db-influxdb.powerp.svc.ooclab.io:8086;
        }
    }


---
apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: powerp
spec:
  selector:
    app: nginx-router
  ports:
  - port: 8086
    targetPort: 80


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: powerp
  labels:
    name: nginx-gateway
    app: nginx-router
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nginx-gateway
        app: nginx-router
    spec:
      containers:
      - name: nginx-gateway
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: router-cfg
      volumes:
      - name: router-cfg
        configMap:
          name: nginx-router-cfg
