---
apiVersion: v1
kind: Namespace
metadata:
  name: powerp

---
apiVersion: v1
kind: Service
metadata:
  name: s27-influxdb
  namespace: powerp
spec:
  selector:
    role: s27-influxdb
  ports:
  - port: 8086
    targetPort: 8086

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: s27-influxdb
  namespace: powerp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: s27-influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb
        imagePullPolicy: Always
        ports:
          - containerPort: 8086
        volumeMounts:
          - mountPath: /var/lib/influxdb
            name: s27-data
      volumes:
        - name: s27-data
          hostPath:
            path: /data/product/powerp/influxdb/s76
